# Generated by Django 5.1.1 on 2024-09-26 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveSmallIntegerField(db_default=1)),
                ('phone', models.CharField(max_length=12)),
                ('full_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('yangi', 'YANGI'), ('Dastavaga tayyor', 'DASTAVKAGA TAYYOR'), ('yetkazilmoqda', 'YETKAZILMOQDA'), ('yetkazib_berildi', 'YETKAZIB_BERILDI'), ('telefon_kotarmadi', 'TELEFON_KOTARMADI'), ('bekor_qilindi', 'BEKOR_QILINDI'), ('arxivlandi', 'ARXIVLANDI')], default='yangi', max_length=255)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.district')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.product')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.region')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
