# Generated by Django 5.1.1 on 2024-10-04 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_order_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('yangi', 'YANGI'), ('Dastavkaga tayyor', 'DASTAVKAGA TAYYOR'), ('yetkazilmoqda', 'YETKAZILMOQDA'), ('yetkazib_berildi', 'YETKAZIB_BERILDI'), ("telefon_ko'tarmadi", "TELEFON_KO'TARMADI"), ('bekor_qilindi', 'BEKOR_QILINDI'), ('arxivlandi', 'ARXIVLANDI')], default='yangi', max_length=255),
        ),
        migrations.AlterField(
            model_name='stream',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='apps.product'),
        ),
    ]
