# Generated by Django 5.1.1 on 2024-10-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_order_owner_alter_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_started', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
