# Generated by Django 5.1.1 on 2024-10-04 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_concurs'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDeliveryPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_for_all_regions', models.PositiveIntegerField(db_default=0, verbose_name='Barcha Viloyatlar Uchun Yetkazib Berish Narxi')),
                ('price_for_tashkent_region', models.PositiveIntegerField(db_default=0, verbose_name='Toshkent Viloyati Uchun Yetkazib Berish Narxi')),
                ('price_for_inside_of_tashkent', models.PositiveIntegerField(db_default=0, verbose_name='Toshkent Shahar Ichiga Yetkazish Narxi')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='categories/%Y/%m/%d', verbose_name='Kategoriya rasmi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='concurs',
            name='about',
            field=models.TextField(verbose_name='Musobaqa haqida'),
        ),
        migrations.AlterField(
            model_name='concurs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan Vaqti'),
        ),
        migrations.AlterField(
            model_name='concurs',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Musobaqa Tugash Vaqti'),
        ),
        migrations.AlterField(
            model_name='concurs',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='Musobaqa Rasmi'),
        ),
        migrations.AlterField(
            model_name='concurs',
            name='is_started',
            field=models.BooleanField(default=False, verbose_name='Musobaqa holati'),
        ),
        migrations.AlterField(
            model_name='concurs',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Musobaqa Nomi'),
        ),
        migrations.AlterField(
            model_name='concurs',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Musobaqa Boshlanish Vaqti'),
        ),
        migrations.AlterField(
            model_name='concurs',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan Vaqti'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tuman Nomi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan Vaqti'),
        ),
        migrations.AlterField(
            model_name='order',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.district', verbose_name='Buyurtma boradigan tuman'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Buyurtmani Qabul qiluvchi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Mahsulot Beruvchi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Buyurtma qilganing raqami'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.product', verbose_name='Buyurtma mahsuloti'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveSmallIntegerField(db_default=1, verbose_name='Buyurtma soni'),
        ),
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.region', verbose_name='Buyurtma boradigan shahar'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('yangi', 'YANGI'), ('Dastavkaga tayyor', 'DASTAVKAGA TAYYOR'), ('yetkazilmoqda', 'YETKAZILMOQDA'), ('yetkazib_berildi', 'YETKAZIB_BERILDI'), ('telefon_kotarmadi', 'TELEFON_KOTARMADI'), ('bekor_qilindi', 'BEKOR_QILINDI'), ('arxivlandi', 'ARXIVLANDI')], default='yangi', max_length=255, verbose_name='Buyurtma holati'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='apps.stream', verbose_name='Buyurtmaning oqimi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan Vaqti'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='apps.category', verbose_name='Mahsulot Kategoriyasi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan Vaqti'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Mahsulot haqida'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/%Y/%m/%d', verbose_name='Mahsulot Rasmi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='payment_referral',
            field=models.PositiveIntegerField(blank=True, default=0, help_text="so'mda", null=True, verbose_name='Oqim egasiga beriladigan pul'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveSmallIntegerField(verbose_name='Mahsulot narxi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveSmallIntegerField(verbose_name='Mahsulot Soni'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan Vaqti'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Viloyat Nomi'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan Vaqti'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='discount',
            field=models.PositiveSmallIntegerField(db_default=0, verbose_name='Oqim Chegirmasi'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='name',
            field=models.CharField(max_length=255, verbose_name="Oqim Nomi (link ko'rinishida) "),
        ),
        migrations.AlterField(
            model_name='stream',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Oqimnning Egasi'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='apps.product', verbose_name='Oqimning Mahsuloti'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='tashrif',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Oqimning Tashriflar Soni'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan Vaqti'),
        ),
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='User Haqida'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User Manzili'),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.district', verbose_name='User Tumani'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='User Rasmi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, unique=True, verbose_name='User Telefon Raqami'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='User Telegram Id si'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('operator', 'Operator'), ('manager', 'Manager'), ('admin_side', 'Admin_side'), ('currier', 'Currier'), ('user', 'User')], default='user', max_length=25, verbose_name='Userning turi'),
        ),
    ]
