# Generated by Django 5.1.1 on 2024-10-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_sitedeliveryprices_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_market',
            field=models.TextField(blank=True, null=True, verbose_name='Market Page Uchun Chegrima'),
        ),
    ]
