# Generated by Django 5.1.1 on 2024-10-07 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_user_balance_alter_order_owner_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user',
            new_name='owner',
        ),
    ]
