# Generated by Django 5.1.1 on 2024-10-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_orderproxyarchived_orderproxycanceled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('yangi', 'YANGI'), ('tayyor', 'TAYYOR'), ('yetkazilmoqda', 'YETKAZILMOQDA'), ('yetkazib_berildi', 'YETKAZIB_BERILDI'), ('telefon_kotarmadi', 'TELEFON_KOTARMADI'), ('bekor_qilindi', 'BEKOR_QILINDI'), ('arxivlandi', 'ARXIVLANDI')], default='yangi', max_length=255, verbose_name='Buyurtma holati'),
        ),
        migrations.DeleteModel(
            name='CurrierProfile',
        ),
    ]
