# Generated by Django 5.1.1 on 2024-10-21 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_product_managers_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproxycanceled',
            name='order_ptr',
        ),
        migrations.RemoveField(
            model_name='orderproxydelivered',
            name='order_ptr',
        ),
        migrations.RemoveField(
            model_name='orderproxydelivering',
            name='order_ptr',
        ),
        migrations.RemoveField(
            model_name='orderproxynew',
            name='order_ptr',
        ),
        migrations.RemoveField(
            model_name='orderproxyready',
            name='order_ptr',
        ),
        migrations.RemoveField(
            model_name='userproxyadminmodel',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='userproxydrivermodel',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='userproxymanagermodel',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='userproxyoperatormodel',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='userproxyusermodel',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='OrderProxyArchived',
        ),
        migrations.DeleteModel(
            name='OrderProxyCanceled',
        ),
        migrations.DeleteModel(
            name='OrderProxyDelivered',
        ),
        migrations.DeleteModel(
            name='OrderProxyDelivering',
        ),
        migrations.DeleteModel(
            name='OrderProxyNew',
        ),
        migrations.DeleteModel(
            name='OrderProxyReady',
        ),
        migrations.DeleteModel(
            name='UserProxyAdminModel',
        ),
        migrations.DeleteModel(
            name='UserProxyDriverModel',
        ),
        migrations.DeleteModel(
            name='UserProxyManagerModel',
        ),
        migrations.DeleteModel(
            name='UserProxyOperatorModel',
        ),
        migrations.DeleteModel(
            name='UserProxyUserModel',
        ),
    ]
